
# (PART\*) Guide for Learners {-}

# About Leanpub

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/what_is_leanpub.Rmd",
  branch = "formatting",
  repo_name = "fhdsl/Using_Leanpub"
)
```

# Make a Leanpub Account

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/make_an_account.Rmd",
  branch = "formatting",
  repo_name = "fhdsl/Using_Leanpub"
)
```

# Find a Course

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/find_a_course.Rmd",
  branch = "formatting",
  repo_name = "fhdsl/Using_Leanpub"
)
```

:::: {.notice}
```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/hutch_homepage.Rmd",
  branch = "formatting",
  repo_name = "fhdsl/Using_Leanpub"
)
```
::::

# Start a Course

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/start_a_course.Rmd",
  branch = "formatting",
  repo_name = "fhdsl/Using_Leanpub"
)
```

# Navigate a Course

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/navigate_a_course.Rmd",
  branch = "formatting",
  repo_name = "fhdsl/Using_Leanpub"
)
```

# Get a Certificate of Completion

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/get_a_certificate.Rmd",
  branch = "formatting",
  repo_name = "fhdsl/Using_Leanpub"
)
```

# (PART\*) Guide for Course Developers {-}

# Organizational Accounts

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/check_org_account.Rmd",
  branch = "formatting",
  repo_name = "fhdsl/Using_Leanpub"
)
```

# Add Organization Editor

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/add_org_editor.Rmd",
  branch = "formatting",
  repo_name = "fhdsl/Using_Leanpub"
)
```

